version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: integrador
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sistema-network

  backend:
    build:
      context: ./Sistema-inte-main
    container_name: sistema-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/integrador
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - sistema-network

  frontend:
    build:
      context: ./front-residencial  
    container_name: sistema-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - sistema-network

volumes:
  mysql_data:

networks:
  sistema-network:
    driver: bridge
